- name: Install and configure Promtail on remote servers
  hosts: all
  become: yes
  vars:
    loki_server_url: "http://27.107.225.60:3100/loki/api/v1/push"

  tasks:
    - name: Install dependencies
      apt:
        name: [ "wget", "unzip" ]
        state: present
        update_cache: yes

    - name: Download Promtail binary
      get_url:
        url: "https://github.com/grafana/loki/releases/latest/download/promtail-linux-amd64.zip"
        dest: "/tmp/promtail.zip"
        mode: '0644'

    - name: Extract Promtail
      unarchive:
        src: "/tmp/promtail.zip"
        dest: "/usr/local/bin/"
        remote_src: yes
      notify:
        - Restart promtail

    - name: Rename binary
      command: mv /usr/local/bin/promtail-linux-amd64 /usr/local/bin/promtail
      args:
        creates: /usr/local/bin/promtail

    - name: Make Promtail executable
      file:
        path: /usr/local/bin/promtail
        mode: '0755'

    - name: Create Promtail config directory
      file:
        path: /etc/promtail
        state: directory

    - name: Configure Promtail to send PM2 logs to Loki
      copy:
        dest: /etc/promtail/config.yml
        content: |
          server:
            http_listen_port: 9080
            grpc_listen_port: 0

          positions:
            filename: /tmp/positions.yaml

          clients:
            - url: "{{ loki_server_url }}"

          scrape_configs:
            - job_name: pm2_logs
              static_configs:
                - targets:
                    - localhost
                  labels:
                    job: pm2
                    host: "{{ ansible_hostname }}"
                    __path__: /root/.pm2/logs/*.log

    - name: Create systemd service for Promtail
      copy:
        dest: /etc/systemd/system/promtail.service
        content: |
          [Unit]
          Description=Promtail Log Shipper
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/promtail --config.file=/etc/promtail/config.yml
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start Promtail
      systemd:
        name: promtail
        enabled: yes
        state: restarted

  handlers:
    - name: Restart promtail
      systemd:
        name: promtail
        state: restarted
